version: "3.3"
services:
  db:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_PASSWORD: fctop
      MYSQL_DATABASE: fctop
      MYSQL_PASSWORD: fctop
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3306:3306"
  server:
    build:
      context: ./server
    ports:
      - "5050:5050"

  client:
    build:
      context: ./client
    ports:
      - "80:3000"
