version: "3.9"
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: fctop
      MYSQL_DATABASE: fctop
      # MYSQL_USER: root
      MYSQL_PASSWORD: fctop
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3306:3306"
  server:
    build:
      context: ./server
    ports:
      - "5050:5050"

